"""init

Revision ID: af4221fbb29e
Revises:
Create Date: 2025-07-07 19:30:37.060002

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "af4221fbb29e"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "relationship_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_relationship_types")),
        sa.UniqueConstraint("name", name=op.f("uq_relationship_types_name")),
    )
    op.create_table(
        "requirement_priorities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("level", sa.Integer(), nullable=True),
        sa.Column("color", sa.String(length=20), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_requirement_priorities")),
        sa.UniqueConstraint("name", name=op.f("uq_requirement_priorities_name")),
    )
    op.create_table(
        "requirement_statuses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("color", sa.String(length=20), nullable=True),
        sa.Column("is_final", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("workflow_transitions", sa.ARRAY(sa.Integer()), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_requirement_statuses")),
        sa.UniqueConstraint("name", name=op.f("uq_requirement_statuses_name")),
    )
    op.create_table(
        "requirement_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_requirement_types")),
        sa.UniqueConstraint("name", name=op.f("uq_requirement_types_name")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "username",
            sa.String(length=50),
            nullable=False,
            comment="Уникальное имя пользователя",
        ),
        sa.Column(
            "email",
            sa.String(length=100),
            nullable=False,
            comment="Email адрес пользователя",
        ),
        sa.Column(
            "hashed_password",
            sa.String(length=128),
            nullable=False,
            comment="Хэшированный пароль",
        ),
        sa.Column(
            "name",
            sa.String(length=100),
            nullable=True,
            comment="Полное имя пользователя",
        ),
        sa.Column(
            "first_name",
            sa.String(length=100),
            nullable=True,
            comment="Имя пользователя",
        ),
        sa.Column(
            "last_name",
            sa.String(length=100),
            nullable=True,
            comment="Фамилия пользователя",
        ),
        sa.Column(
            "department",
            sa.String(length=100),
            nullable=True,
            comment="Отдел пользователя",
        ),
        sa.Column(
            "phone", sa.String(length=20), nullable=True, comment="Телефон пользователя"
        ),
        sa.Column(
            "role",
            sa.String(length=20),
            nullable=False,
            comment="Роль пользователя (admin, manager, analyst, developer, tester, user)",
        ),
        sa.Column(
            "is_active", sa.Boolean(), nullable=False, comment="Активен ли пользователь"
        ),
        sa.Column(
            "is_superuser",
            sa.Boolean(),
            nullable=False,
            comment="Является ли пользователь суперпользователем",
        ),
        sa.Column(
            "email_verified",
            sa.Boolean(),
            nullable=False,
            comment="Подтвержден ли email пользователя",
        ),
        sa.Column(
            "email_verified_at",
            sa.DateTime(),
            nullable=True,
            comment="Время подтверждения email",
        ),
        sa.Column(
            "last_login",
            sa.DateTime(),
            nullable=True,
            comment="Время последнего входа в систему",
        ),
        sa.Column(
            "created_at", sa.DateTime(), nullable=False, comment="Время создания записи"
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
            comment="Время последнего обновления записи",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
        sa.UniqueConstraint("username", name=op.f("uq_users_username")),
    )
    op.create_index("ix_users_email_unique", "users", ["email"], unique=True)
    op.create_index(
        "ix_users_email_verified", "users", ["email_verified"], unique=False
    )
    op.create_index("ix_users_is_active", "users", ["is_active"], unique=False)
    op.create_index("ix_users_last_login", "users", ["last_login"], unique=False)
    op.create_index(
        "ix_users_role_created", "users", ["role", "created_at"], unique=False
    )
    op.create_index("ix_users_username_unique", "users", ["username"], unique=True)
    op.create_table(
        "dashboard_widgets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("widget_type", sa.String(length=50), nullable=False),
        sa.Column("widget_title", sa.String(length=100), nullable=False),
        sa.Column("position", sa.Integer(), nullable=True),
        sa.Column("size", sa.String(length=20), nullable=True),
        sa.Column("is_visible", sa.Boolean(), nullable=True),
        sa.Column("config", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_dashboard_widgets_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dashboard_widgets")),
    )
    op.create_index(
        op.f("ix_dashboard_widgets_id"), "dashboard_widgets", ["id"], unique=False
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "token",
            sa.String(length=255),
            nullable=False,
            comment="Уникальный токен обновления",
        ),
        sa.Column("user_id", sa.Integer(), nullable=False, comment="ID пользователя"),
        sa.Column(
            "created_at", sa.DateTime(), nullable=False, comment="Время создания токена"
        ),
        sa.Column(
            "expires_at",
            sa.DateTime(),
            nullable=False,
            comment="Время истечения токена",
        ),
        sa.Column(
            "last_used_at",
            sa.DateTime(),
            nullable=True,
            comment="Время последнего использования токена",
        ),
        sa.Column(
            "is_active", sa.Boolean(), nullable=False, comment="Активен ли токен"
        ),
        sa.Column("user_agent", sa.Text(), nullable=True, comment="User-Agent клиента"),
        sa.Column(
            "ip_address",
            sa.String(length=45),
            nullable=True,
            comment="IP адрес клиента",
        ),
        sa.Column(
            "revoked_at", sa.DateTime(), nullable=True, comment="Время отзыва токена"
        ),
        sa.Column(
            "revoked_by",
            sa.String(length=50),
            nullable=True,
            comment="Причина отзыва токена",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_refresh_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
        sa.UniqueConstraint("token", name=op.f("uq_refresh_tokens_token")),
    )
    op.create_index(
        "ix_refresh_tokens_expires_at", "refresh_tokens", ["expires_at"], unique=False
    )
    op.create_index(
        "ix_refresh_tokens_is_active", "refresh_tokens", ["is_active"], unique=False
    )
    op.create_index(
        "ix_refresh_tokens_token_unique", "refresh_tokens", ["token"], unique=True
    )
    op.create_index(
        "ix_refresh_tokens_user_active",
        "refresh_tokens",
        ["user_id", "is_active"],
        unique=False,
    )
    op.create_index(
        "ix_refresh_tokens_user_id", "refresh_tokens", ["user_id"], unique=False
    )
    op.create_table(
        "teams",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "name", sa.String(length=100), nullable=False, comment="Название команды"
        ),
        sa.Column(
            "code",
            sa.String(length=50),
            nullable=False,
            comment="Уникальный код команды",
        ),
        sa.Column("description", sa.Text(), nullable=True, comment="Описание команды"),
        sa.Column(
            "status", sa.String(length=20), nullable=False, comment="Статус команды"
        ),
        sa.Column(
            "is_public", sa.Boolean(), nullable=False, comment="Публичная ли команда"
        ),
        sa.Column(
            "max_members",
            sa.Integer(),
            nullable=True,
            comment="Максимальное количество участников",
        ),
        sa.Column("owner_id", sa.Integer(), nullable=False, comment="Владелец команды"),
        sa.Column(
            "created_at", sa.DateTime(), nullable=False, comment="Время создания записи"
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
            comment="Время последнего обновления записи",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_teams_owner_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_teams")),
        sa.UniqueConstraint("code", name=op.f("uq_teams_code")),
    )
    op.create_index("ix_teams_code_unique", "teams", ["code"], unique=True)
    op.create_index("ix_teams_name", "teams", ["name"], unique=False)
    op.create_index(
        "ix_teams_owner_status", "teams", ["owner_id", "status"], unique=False
    )
    op.create_index(
        "ix_teams_status_created", "teams", ["status", "created_at"], unique=False
    )
    op.create_table(
        "user_dashboard_preferences",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("show_quick_stats", sa.Boolean(), nullable=True),
        sa.Column("show_recent_activity", sa.Boolean(), nullable=True),
        sa.Column("show_my_projects", sa.Boolean(), nullable=True),
        sa.Column("show_pending_approvals", sa.Boolean(), nullable=True),
        sa.Column("default_project_filter", sa.String(length=100), nullable=True),
        sa.Column("activity_limit", sa.Integer(), nullable=True),
        sa.Column("refresh_interval", sa.Integer(), nullable=True),
        sa.Column("theme", sa.String(length=20), nullable=True),
        sa.Column("notifications_enabled", sa.Boolean(), nullable=True),
        sa.Column("email_notifications", sa.Boolean(), nullable=True),
        sa.Column("timezone", sa.String(length=50), nullable=True),
        sa.Column("custom_settings", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_dashboard_preferences_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_dashboard_preferences")),
        sa.UniqueConstraint(
            "user_id", name=op.f("uq_user_dashboard_preferences_user_id")
        ),
    )
    op.create_index(
        op.f("ix_user_dashboard_preferences_id"),
        "user_dashboard_preferences",
        ["id"],
        unique=False,
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "code",
            sa.String(length=50),
            nullable=False,
            comment="Уникальный код проекта",
        ),
        sa.Column(
            "name", sa.String(length=100), nullable=False, comment="Название проекта"
        ),
        sa.Column("description", sa.Text(), nullable=True, comment="Описание проекта"),
        sa.Column(
            "status", sa.String(length=50), nullable=False, comment="Статус проекта"
        ),
        sa.Column("owner_id", sa.Integer(), nullable=False, comment="Владелец проекта"),
        sa.Column("team_id", sa.Integer(), nullable=True, comment="Команда проекта"),
        sa.Column(
            "created_at", sa.DateTime(), nullable=False, comment="Время создания записи"
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
            comment="Время последнего обновления записи",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_projects_owner_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
            name=op.f("fk_projects_team_id_teams"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
        sa.UniqueConstraint("code", name=op.f("uq_projects_code")),
    )
    op.create_index("ix_projects_code_unique", "projects", ["code"], unique=True)
    op.create_index(
        "ix_projects_status_created", "projects", ["status", "created_at"], unique=False
    )
    op.create_table(
        "team_members",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False, comment="ID команды"),
        sa.Column("user_id", sa.Integer(), nullable=False, comment="ID пользователя"),
        sa.Column(
            "role",
            sa.String(length=20),
            nullable=False,
            comment="Роль участника в команде",
        ),
        sa.Column(
            "is_active", sa.Boolean(), nullable=False, comment="Активен ли участник"
        ),
        sa.Column(
            "joined_at",
            sa.DateTime(),
            nullable=False,
            comment="Время присоединения к команде",
        ),
        sa.Column(
            "left_at", sa.DateTime(), nullable=True, comment="Время выхода из команды"
        ),
        sa.Column(
            "title",
            sa.String(length=100),
            nullable=True,
            comment="Должность участника в команде",
        ),
        sa.Column(
            "hourly_rate",
            sa.Float(),
            nullable=True,
            comment="Почасовая ставка участника",
        ),
        sa.Column(
            "notes", sa.String(length=500), nullable=True, comment="Заметки о участнике"
        ),
        sa.Column(
            "created_at", sa.DateTime(), nullable=False, comment="Время создания записи"
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
            comment="Время последнего обновления записи",
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
            name=op.f("fk_team_members_team_id_teams"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_team_members_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_team_members")),
    )
    op.create_index(
        "ix_team_members_is_active", "team_members", ["is_active"], unique=False
    )
    op.create_index(
        "ix_team_members_joined_at", "team_members", ["joined_at"], unique=False
    )
    op.create_index(
        "ix_team_members_team_role", "team_members", ["team_id", "role"], unique=False
    )
    op.create_index(
        "ix_team_members_team_user", "team_members", ["team_id", "user_id"], unique=True
    )
    op.create_index(
        "ix_team_members_user_role", "team_members", ["user_id", "role"], unique=False
    )
    op.create_table(
        "releases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column(
            "name", sa.String(length=100), nullable=False, comment="Название релиза"
        ),
        sa.Column(
            "version", sa.String(length=50), nullable=False, comment="SemVer format"
        ),
        sa.Column("description", sa.Text(), nullable=True, comment="Описание релиза"),
        sa.Column(
            "status", sa.String(length=20), nullable=False, comment="Статус релиза"
        ),
        sa.Column(
            "planned_date",
            sa.DateTime(),
            nullable=True,
            comment="Планируемая дата релиза",
        ),
        sa.Column(
            "release_date",
            sa.DateTime(),
            nullable=True,
            comment="Фактическая дата релиза",
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_releases_project_id_projects"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_releases")),
    )
    op.create_table(
        "requirement_groups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_requirement_groups_project_id_projects"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_requirement_groups")),
    )
    op.create_table(
        "specs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "description", sa.Text(), nullable=True, comment="Описание спецификации"
        ),
        sa.Column(
            "version",
            sa.String(length=50),
            nullable=True,
            comment="Версия спецификации",
        ),
        sa.Column(
            "content",
            sa.JSON(),
            nullable=True,
            comment="Содержимое спецификации в JSON формате",
        ),
        sa.Column(
            "format", sa.String(length=20), nullable=True, comment="Формат документа"
        ),
        sa.Column(
            "language", sa.String(length=10), nullable=True, comment="Язык спецификации"
        ),
        sa.Column(
            "status", sa.String(length=50), nullable=True, comment="Статус спецификации"
        ),
        sa.Column(
            "generated_by", sa.Integer(), nullable=True, comment="Создана пользователем"
        ),
        sa.Column(
            "template_id", sa.Integer(), nullable=True, comment="Шаблон спецификации"
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=True,
            comment="Время последнего обновления",
        ),
        sa.ForeignKeyConstraint(
            ["generated_by"], ["users.id"], name=op.f("fk_specs_generated_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_specs_project_id_projects")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_specs")),
    )
    op.create_table(
        "requirement_group_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "snapshot_data",
            sa.JSON(),
            nullable=False,
            comment="Снимок группы требований и связей",
        ),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_requirement_group_versions_created_by_users"),
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["requirement_groups.id"],
            name=op.f("fk_requirement_group_versions_group_id_requirement_groups"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_requirement_group_versions")),
    )
    op.create_table(
        "requirements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "title",
            sa.String(length=200),
            nullable=False,
            comment="Заголовок требования",
        ),
        sa.Column(
            "description",
            sa.Text(),
            nullable=True,
            comment="Подробное описание требования",
        ),
        sa.Column(
            "deadline",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Срок выполнения требования",
        ),
        sa.Column(
            "progress",
            sa.Float(),
            nullable=False,
            comment="Прогресс выполнения требования (0.0-100.0)",
        ),
        sa.Column("type_id", sa.Integer(), nullable=False, comment="Тип требования"),
        sa.Column(
            "priority_id", sa.Integer(), nullable=False, comment="Приоритет требования"
        ),
        sa.Column(
            "status_id", sa.Integer(), nullable=False, comment="Статус требования"
        ),
        sa.Column(
            "project_id",
            sa.Integer(),
            nullable=False,
            comment="Проект, к которому относится требование",
        ),
        sa.Column(
            "author_id", sa.Integer(), nullable=False, comment="Автор требования"
        ),
        sa.Column(
            "last_modified_by",
            sa.Integer(),
            nullable=False,
            comment="Последний редактор требования",
        ),
        sa.Column(
            "release_id",
            sa.Integer(),
            nullable=True,
            comment="Релиз, в котором реализуется требование",
        ),
        sa.Column(
            "spec_id",
            sa.Integer(),
            nullable=True,
            comment="Спецификация, к которой относится требование",
        ),
        sa.Column(
            "created_at", sa.DateTime(), nullable=False, comment="Время создания записи"
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
            comment="Время последнего обновления записи",
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
            name=op.f("fk_requirements_author_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["last_modified_by"],
            ["users.id"],
            name=op.f("fk_requirements_last_modified_by_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["priority_id"],
            ["requirement_priorities.id"],
            name=op.f("fk_requirements_priority_id_requirement_priorities"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_requirements_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["releases.id"],
            name=op.f("fk_requirements_release_id_releases"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["spec_id"],
            ["specs.id"],
            name=op.f("fk_requirements_spec_id_specs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["status_id"],
            ["requirement_statuses.id"],
            name=op.f("fk_requirements_status_id_requirement_statuses"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["type_id"],
            ["requirement_types.id"],
            name=op.f("fk_requirements_type_id_requirement_types"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_requirements")),
    )
    op.create_index(
        "ix_requirements_author_created",
        "requirements",
        ["author_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_requirements_project_status",
        "requirements",
        ["project_id", "status_id"],
        unique=False,
    )
    op.create_table(
        "comments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("requirement_id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"], ["users.id"], name=op.f("fk_comments_author_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["requirement_id"],
            ["requirements.id"],
            name=op.f("fk_comments_requirement_id_requirements"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_comments")),
    )
    op.create_table(
        "dashboard_activities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("activity_type", sa.String(length=50), nullable=False),
        sa.Column("activity_title", sa.String(length=200), nullable=False),
        sa.Column("activity_description", sa.Text(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("user_name", sa.String(length=100), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("requirement_id", sa.Integer(), nullable=True),
        sa.Column("team_id", sa.Integer(), nullable=True),
        sa.Column("entity_type", sa.String(length=50), nullable=True),
        sa.Column("entity_id", sa.Integer(), nullable=True),
        sa.Column("entity_name", sa.String(length=200), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("priority", sa.String(length=20), nullable=True),
        sa.Column("extra_data", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_dashboard_activities_project_id_projects"),
        ),
        sa.ForeignKeyConstraint(
            ["requirement_id"],
            ["requirements.id"],
            name=op.f("fk_dashboard_activities_requirement_id_requirements"),
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
            name=op.f("fk_dashboard_activities_team_id_teams"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_dashboard_activities_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dashboard_activities")),
    )
    op.create_index(
        op.f("ix_dashboard_activities_id"), "dashboard_activities", ["id"], unique=False
    )
    op.create_table(
        "dashboard_notifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("action_url", sa.String(length=255), nullable=True),
        sa.Column("action_text", sa.String(length=100), nullable=True),
        sa.Column("is_read", sa.Boolean(), nullable=True),
        sa.Column("priority", sa.String(length=20), nullable=True),
        sa.Column("project_id", sa.Integer(), nullable=True),
        sa.Column("requirement_id", sa.Integer(), nullable=True),
        sa.Column("team_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("read_at", sa.DateTime(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_dashboard_notifications_project_id_projects"),
        ),
        sa.ForeignKeyConstraint(
            ["requirement_id"],
            ["requirements.id"],
            name=op.f("fk_dashboard_notifications_requirement_id_requirements"),
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
            name=op.f("fk_dashboard_notifications_team_id_teams"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_dashboard_notifications_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dashboard_notifications")),
    )
    op.create_index(
        op.f("ix_dashboard_notifications_id"),
        "dashboard_notifications",
        ["id"],
        unique=False,
    )
    op.create_table(
        "relationships",
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("target_id", sa.Integer(), nullable=False),
        sa.Column("type_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["requirements.id"],
            name=op.f("fk_relationships_source_id_requirements"),
        ),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["requirements.id"],
            name=op.f("fk_relationships_target_id_requirements"),
        ),
        sa.ForeignKeyConstraint(
            ["type_id"],
            ["relationship_types.id"],
            name=op.f("fk_relationships_type_id_relationship_types"),
        ),
        sa.PrimaryKeyConstraint(
            "source_id", "target_id", "type_id", name=op.f("pk_relationships")
        ),
    )
    op.create_table(
        "test_results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "NOT_STARTED",
                "IN_PROGRESS",
                "PASSED",
                "FAILED",
                "BLOCKED",
                name="teststatus",
            ),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("external_id", sa.String(length=50), nullable=True),
        sa.Column("requirement_id", sa.Integer(), nullable=False),
        sa.Column("tester_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["requirement_id"],
            ["requirements.id"],
            name=op.f("fk_test_results_requirement_id_requirements"),
        ),
        sa.ForeignKeyConstraint(
            ["tester_id"], ["users.id"], name=op.f("fk_test_results_tester_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_test_results")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("test_results")
    op.drop_table("relationships")
    op.drop_index(
        op.f("ix_dashboard_notifications_id"), table_name="dashboard_notifications"
    )
    op.drop_table("dashboard_notifications")
    op.drop_index(op.f("ix_dashboard_activities_id"), table_name="dashboard_activities")
    op.drop_table("dashboard_activities")
    op.drop_table("comments")
    op.drop_index("ix_requirements_project_status", table_name="requirements")
    op.drop_index("ix_requirements_author_created", table_name="requirements")
    op.drop_table("requirements")
    op.drop_table("requirement_group_versions")
    op.drop_table("specs")
    op.drop_table("requirement_groups")
    op.drop_table("releases")
    op.drop_index("ix_team_members_user_role", table_name="team_members")
    op.drop_index("ix_team_members_team_user", table_name="team_members")
    op.drop_index("ix_team_members_team_role", table_name="team_members")
    op.drop_index("ix_team_members_joined_at", table_name="team_members")
    op.drop_index("ix_team_members_is_active", table_name="team_members")
    op.drop_table("team_members")
    op.drop_index("ix_projects_status_created", table_name="projects")
    op.drop_index("ix_projects_code_unique", table_name="projects")
    op.drop_table("projects")
    op.drop_index(
        op.f("ix_user_dashboard_preferences_id"),
        table_name="user_dashboard_preferences",
    )
    op.drop_table("user_dashboard_preferences")
    op.drop_index("ix_teams_status_created", table_name="teams")
    op.drop_index("ix_teams_owner_status", table_name="teams")
    op.drop_index("ix_teams_name", table_name="teams")
    op.drop_index("ix_teams_code_unique", table_name="teams")
    op.drop_table("teams")
    op.drop_index("ix_refresh_tokens_user_id", table_name="refresh_tokens")
    op.drop_index("ix_refresh_tokens_user_active", table_name="refresh_tokens")
    op.drop_index("ix_refresh_tokens_token_unique", table_name="refresh_tokens")
    op.drop_index("ix_refresh_tokens_is_active", table_name="refresh_tokens")
    op.drop_index("ix_refresh_tokens_expires_at", table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index(op.f("ix_dashboard_widgets_id"), table_name="dashboard_widgets")
    op.drop_table("dashboard_widgets")
    op.drop_index("ix_users_username_unique", table_name="users")
    op.drop_index("ix_users_role_created", table_name="users")
    op.drop_index("ix_users_last_login", table_name="users")
    op.drop_index("ix_users_is_active", table_name="users")
    op.drop_index("ix_users_email_verified", table_name="users")
    op.drop_index("ix_users_email_unique", table_name="users")
    op.drop_table("users")
    op.drop_table("requirement_types")
    op.drop_table("requirement_statuses")
    op.drop_table("requirement_priorities")
    op.drop_table("relationship_types")
    # ### end Alembic commands ###
