"""add role dag

Revision ID: dcea0f96f1eb
Revises: 703becde7234
Create Date: 2025-08-16 13:24:56.158361

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dcea0f96f1eb"
down_revision: Union[str, None] = "703becde7234"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "role_hierarchy_cache",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False, comment="ID роли"),
        sa.Column(
            "cache_type",
            sa.String(length=50),
            nullable=False,
            comment="Тип кеша (ancestors, descendants, permissions)",
        ),
        sa.Column(
            "cache_data", sa.JSON(), nullable=False, comment="Кешированные данные"
        ),
        sa.Column("is_valid", sa.Boolean(), nullable=False, comment="Валиден ли кеш"),
        sa.Column(
            "expires_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Дата истечения кеша",
        ),
        sa.Column(
            "created_at", sa.DateTime(), nullable=False, comment="Время создания записи"
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
            comment="Время последнего обновления записи",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["enhanced_roles.id"],
            name=op.f("fk_role_hierarchy_cache_role_id_enhanced_roles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_role_hierarchy_cache")),
    )
    op.create_index(
        "ix_role_hierarchy_cache_cache_type",
        "role_hierarchy_cache",
        ["cache_type"],
        unique=False,
    )
    op.create_index(
        "ix_role_hierarchy_cache_is_valid",
        "role_hierarchy_cache",
        ["is_valid"],
        unique=False,
    )
    op.create_index(
        "ix_role_hierarchy_cache_role_id",
        "role_hierarchy_cache",
        ["role_id"],
        unique=False,
    )
    op.create_table(
        "role_hierarchy",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "parent_role_id",
            sa.Integer(),
            nullable=False,
            comment="ID родительской роли",
        ),
        sa.Column(
            "child_role_id", sa.Integer(), nullable=False, comment="ID дочерней роли"
        ),
        sa.Column(
            "inheritance_type",
            sa.String(length=20),
            nullable=False,
            comment="Тип наследования разрешений",
        ),
        sa.Column(
            "priority",
            sa.Integer(),
            nullable=False,
            comment="Приоритет наследования (при множественном наследовании)",
        ),
        sa.Column(
            "conditions",
            sa.JSON(),
            nullable=True,
            comment="Условия наследования (JSON)",
        ),
        sa.Column(
            "inherited_permissions",
            sa.JSON(),
            nullable=True,
            comment="Список наследуемых разрешений (для PARTIAL)",
        ),
        sa.Column(
            "excluded_permissions",
            sa.JSON(),
            nullable=True,
            comment="Список исключаемых разрешений (для RESTRICT)",
        ),
        sa.Column(
            "permission_overrides",
            sa.JSON(),
            nullable=True,
            comment="Переопределения разрешений (для OVERRIDE)",
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            comment="Активна ли связь наследования",
        ),
        sa.Column(
            "description",
            sa.Text(),
            nullable=True,
            comment="Описание связи наследования",
        ),
        sa.Column(
            "effective_from",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Дата начала действия наследования",
        ),
        sa.Column(
            "effective_until",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Дата окончания действия наследования",
        ),
        sa.Column(
            "created_by", sa.Integer(), nullable=True, comment="Кем создана связь"
        ),
        sa.Column(
            "created_at", sa.DateTime(), nullable=False, comment="Время создания записи"
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
            comment="Время последнего обновления записи",
        ),
        sa.CheckConstraint(
            "parent_role_id != child_role_id",
            name=op.f("ck_role_hierarchy_ck_role_hierarchy_no_self_reference"),
        ),
        sa.ForeignKeyConstraint(
            ["child_role_id"],
            ["enhanced_roles.id"],
            name=op.f("fk_role_hierarchy_child_role_id_enhanced_roles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_role_hierarchy_created_by_users"),
        ),
        sa.ForeignKeyConstraint(
            ["parent_role_id"],
            ["enhanced_roles.id"],
            name=op.f("fk_role_hierarchy_parent_role_id_enhanced_roles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_role_hierarchy")),
        sa.UniqueConstraint(
            "parent_role_id", "child_role_id", name="uq_role_hierarchy_parent_child"
        ),
    )
    op.create_index(
        "ix_role_hierarchy_child_role_id",
        "role_hierarchy",
        ["child_role_id"],
        unique=False,
    )
    op.create_index(
        "ix_role_hierarchy_inheritance_type",
        "role_hierarchy",
        ["inheritance_type"],
        unique=False,
    )
    op.create_index(
        "ix_role_hierarchy_is_active", "role_hierarchy", ["is_active"], unique=False
    )
    op.create_index(
        "ix_role_hierarchy_parent_role_id",
        "role_hierarchy",
        ["parent_role_id"],
        unique=False,
    )
    op.create_index(
        "ix_role_hierarchy_priority", "role_hierarchy", ["priority"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_role_hierarchy_priority", table_name="role_hierarchy")
    op.drop_index("ix_role_hierarchy_parent_role_id", table_name="role_hierarchy")
    op.drop_index("ix_role_hierarchy_is_active", table_name="role_hierarchy")
    op.drop_index("ix_role_hierarchy_inheritance_type", table_name="role_hierarchy")
    op.drop_index("ix_role_hierarchy_child_role_id", table_name="role_hierarchy")
    op.drop_table("role_hierarchy")
    op.drop_index("ix_role_hierarchy_cache_role_id", table_name="role_hierarchy_cache")
    op.drop_index("ix_role_hierarchy_cache_is_valid", table_name="role_hierarchy_cache")
    op.drop_index(
        "ix_role_hierarchy_cache_cache_type", table_name="role_hierarchy_cache"
    )
    op.drop_table("role_hierarchy_cache")
    # ### end Alembic commands ###
